-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-27 09:09:27 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--student id: 32916221, 32964773, 30052386
--student name: Sohan Jagadeesh, Lee Pui Yin, Vincent Vincent
-- Capture run of script in file called wc_schema_output.txt
set echo on
SPOOL wc_schema_output.txt


DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE journey CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE passenger_address CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE registration CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE temperature CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_availability CASCADE CONSTRAINTS;

DROP TABLE tour_date CASCADE CONSTRAINTS;

DROP TABLE tour_language CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    ship_code      NUMBER(7) NOT NULL,
    cabin_number   NUMBER(7) NOT NULL,
    cabin_capacity NUMBER(7) NOT NULL,
    cabin_class    CHAR(2) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT check_cabin_class CHECK ( cabin_class IN ( 'B', 'I', 'OC', 'S' ) );

COMMENT ON COLUMN cabin.ship_code IS
    'Ship code';

COMMENT ON COLUMN cabin.cabin_number IS
    'Cabin number';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'Cabin capacity';

COMMENT ON COLUMN cabin.cabin_class IS
    'Cabin class';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_number,
                                                        ship_code );

CREATE TABLE country (
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN country.country_code IS
    'Country Code stored as ISO 3166-1 Alpha-2 Codes';

COMMENT ON COLUMN country.country_name IS
    'Country name the port is in';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(7) NOT NULL,
    cruise_name VARCHAR2(50) NOT NULL,
    cruise_desc VARCHAR2(50) NOT NULL,
    ship_code   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN cruise.cruise_name IS
    'Cruise name';

COMMENT ON COLUMN cruise.cruise_desc IS
    'Cruise Description';

COMMENT ON COLUMN cruise.ship_code IS
    'Ship code';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE journey (
    journey_no                 NUMBER(7) NOT NULL,
    cruise_id                  NUMBER(7) NOT NULL,
    port_code                  NUMBER(7) NOT NULL,
    journey_departure_datetime DATE NOT NULL,
    journey_arrival_datetime   DATE NOT NULL
);

COMMENT ON COLUMN journey.journey_no IS
    'Journey Surrogate Key';

COMMENT ON COLUMN journey.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN journey.port_code IS
    'Port code';

COMMENT ON COLUMN journey.journey_departure_datetime IS
    'Cruise departure date and time';

COMMENT ON COLUMN journey.journey_arrival_datetime IS
    'Cruise arrival date and time';

ALTER TABLE journey ADD CONSTRAINT journey_pk PRIMARY KEY ( journey_no );

ALTER TABLE journey
    ADD CONSTRAINT journey_nk UNIQUE ( cruise_id,
                                       port_code,
                                       journey_departure_datetime );

CREATE TABLE language (
    language_code CHAR(2) NOT NULL,
    language_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN language.language_code IS
    'Language based on ISO 639-1 Alpha-2 codes';

COMMENT ON COLUMN language.language_name IS
    'Language name';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( language_code );

CREATE TABLE manifest (
    manifest_no             NUMBER(7) NOT NULL,
    passenger_id            NUMBER(7) NOT NULL,
    cruise_id               NUMBER(7) NOT NULL,
    manifest_board_datetime DATE NOT NULL,
    cabin_number            NUMBER(7) NOT NULL,
    ship_code               NUMBER(7) NOT NULL
);

COMMENT ON COLUMN manifest.manifest_no IS
    'manifest surrogate key';

COMMENT ON COLUMN manifest.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN manifest.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN manifest.manifest_board_datetime IS
    'Passenger boarding date and time';

COMMENT ON COLUMN manifest.cabin_number IS
    'Cabin number';

COMMENT ON COLUMN manifest.ship_code IS
    'Ship code';

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( manifest_no );

ALTER TABLE manifest
    ADD CONSTRAINT manifest_nk UNIQUE ( passenger_id,
                                        cruise_id,
                                        manifest_board_datetime );

CREATE TABLE operator (
    op_id           NUMBER(7) NOT NULL,
    op_company_name VARCHAR2(50) NOT NULL,
    op_ceo_name     VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN operator.op_id IS
    'Operator ID';

COMMENT ON COLUMN operator.op_company_name IS
    'Operator''s company name';

COMMENT ON COLUMN operator.op_ceo_name IS
    'Operator''s CEO name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( op_id );

CREATE TABLE passenger (
    passenger_id           NUMBER(7) NOT NULL,
    passenger_first_name   VARCHAR2(50) NOT NULL,
    passenger_last_name    VARCHAR2(50) NOT NULL,
    passenger_gender       CHAR(6) NOT NULL,
    passenger_dob          DATE NOT NULL,
    passenger_phone_number CHAR(10),
    guardian_id            NUMBER(7),
    padd_no                NUMBER(7) NOT NULL,
    language_code          CHAR(2) NOT NULL
);

COMMENT ON COLUMN passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.passenger_first_name IS
    'Passenger first name';

COMMENT ON COLUMN passenger.passenger_last_name IS
    'Passenger last name';

COMMENT ON COLUMN passenger.passenger_gender IS
    'Passenger gender';

COMMENT ON COLUMN passenger.passenger_dob IS
    'Passenger date of birth';

COMMENT ON COLUMN passenger.passenger_phone_number IS
    'Passenger Phone Number';

COMMENT ON COLUMN passenger.guardian_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.padd_no IS
    'Passenger address surrogate key';

COMMENT ON COLUMN passenger.language_code IS
    'Language based on ISO 639-1 Alpha-2 codes';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id );

CREATE TABLE passenger_address (
    padd_no       NUMBER(7) NOT NULL,
    padd_street   VARCHAR2(50) NOT NULL,
    padd_town     VARCHAR2(50) NOT NULL,
    padd_postcode CHAR(4) NOT NULL,
    country_code  CHAR(2) NOT NULL
);

COMMENT ON COLUMN passenger_address.padd_no IS
    'Passenger address surrogate key';

COMMENT ON COLUMN passenger_address.padd_street IS
    'Passsenger address street (including street name)';

COMMENT ON COLUMN passenger_address.padd_town IS
    'Passenger address town';

COMMENT ON COLUMN passenger_address.padd_postcode IS
    'Passenger address postcode';

COMMENT ON COLUMN passenger_address.country_code IS
    'Country Code stored as ISO 3166-1 Alpha-2 Codes';

ALTER TABLE passenger_address ADD CONSTRAINT passenger_address_pk PRIMARY KEY ( padd_no );

ALTER TABLE passenger_address
    ADD CONSTRAINT passenger_address_nk UNIQUE ( padd_street,
                                                 padd_town,
                                                 padd_postcode,
                                                 country_code );

CREATE TABLE port (
    port_code       NUMBER(7) NOT NULL,
    port_name       VARCHAR2(50) NOT NULL,
    port_population NUMBER(7) NOT NULL,
    port_longitude  NUMBER(10, 7) NOT NULL,
    port_latitude   NUMBER(10, 7) NOT NULL,
    country_code    CHAR(2) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'Port code';

COMMENT ON COLUMN port.port_name IS
    'Port name';

COMMENT ON COLUMN port.port_population IS
    'Port population';

COMMENT ON COLUMN port.port_longitude IS
    'Port longitude';

COMMENT ON COLUMN port.port_latitude IS
    'Port latitude';

COMMENT ON COLUMN port.country_code IS
    'Country Code stored as ISO 3166-1 Alpha-2 Codes';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE registration (
    registration_no  NUMBER(7) NOT NULL,
    tour_date_no     NUMBER(7) NOT NULL,
    passenger_id     NUMBER(7) NOT NULL,
    payment_received CHAR(3) NOT NULL,
    cruise_id        NUMBER(7) NOT NULL
);

COMMENT ON COLUMN registration.registration_no IS
    'registration surrogate key';

COMMENT ON COLUMN registration.tour_date_no IS
    'Tour_date surrogate key';

COMMENT ON COLUMN registration.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN registration.payment_received IS
    'Tour payment received';

COMMENT ON COLUMN registration.cruise_id IS
    'Cruise ID';

ALTER TABLE registration ADD CONSTRAINT regristration_pk PRIMARY KEY ( registration_no );

ALTER TABLE registration ADD CONSTRAINT registration_nk UNIQUE ( tour_date_no,
                                                                 passenger_id );

CREATE TABLE ship (
    ship_code             NUMBER(7) NOT NULL,
    ship_name             VARCHAR2(50) NOT NULL,
    ship_commisioned_date DATE NOT NULL,
    ship_tonnage          NUMBER(7) NOT NULL,
    ship_guest_capacity   NUMBER(7) NOT NULL,
    op_id                 NUMBER(7) NOT NULL,
    country_code          CHAR(2) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'Ship code';

COMMENT ON COLUMN ship.ship_name IS
    'Ship name';

COMMENT ON COLUMN ship.ship_commisioned_date IS
    'Ship commisioned date';

COMMENT ON COLUMN ship.ship_tonnage IS
    'Ship''s tonnage';

COMMENT ON COLUMN ship.ship_guest_capacity IS
    'Ship''s guest capacity';

COMMENT ON COLUMN ship.op_id IS
    'Operator ID';

COMMENT ON COLUMN ship.country_code IS
    'Country Code stored as ISO 3166-1 Alpha-2 Codes';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE temperature (
    port_code     NUMBER(7) NOT NULL,
    temp_month    CHAR(3) NOT NULL,
    temp_avg_high NUMBER(7) NOT NULL,
    temp_avg_low  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN temperature.port_code IS
    'Port code';

COMMENT ON COLUMN temperature.temp_month IS
    'Temperature in month in a particular port (in the first form only the first three letters of a particular month)';

COMMENT ON COLUMN temperature.temp_avg_high IS
    'Temperature average high in a particular port';

COMMENT ON COLUMN temperature.temp_avg_low IS
    'Temperature average low in a particular port';

ALTER TABLE temperature ADD CONSTRAINT temperature_pk PRIMARY KEY ( temp_month,
                                                                    port_code );

CREATE TABLE tour (
    port_code           NUMBER(7) NOT NULL,
    tour_no             NUMBER(7) NOT NULL,
    tour_name           VARCHAR2(50) NOT NULL,
    tour_desc           VARCHAR2(50) NOT NULL,
    tour_hours_req      NUMBER(7, 1) NOT NULL,
    tour_cost_pp        NUMBER(7) NOT NULL,
    tour_wc_access      CHAR(3) NOT NULL,
    tour_start_time     DATE NOT NULL,
    touravailability_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN tour.port_code IS
    'Port code';

COMMENT ON COLUMN tour.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour.tour_name IS
    'Tour name';

COMMENT ON COLUMN tour.tour_desc IS
    'Tour description';

COMMENT ON COLUMN tour.tour_hours_req IS
    'tour hours required';

COMMENT ON COLUMN tour.tour_cost_pp IS
    'Tour cost per person';

COMMENT ON COLUMN tour.tour_wc_access IS
    'Tour wheel chair access';

COMMENT ON COLUMN tour.tour_start_time IS
    'Tour Start Time';

COMMENT ON COLUMN tour.touravailability_id IS
    'Tour availability id (LOOKUP table)';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_no,
                                                      port_code );

CREATE TABLE tour_availability (
    touravailability_id     NUMBER(7) NOT NULL,
    touravailability_status VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN tour_availability.touravailability_id IS
    'Tour availability id (LOOKUP table)';

COMMENT ON COLUMN tour_availability.touravailability_status IS
    'Tour availability';

ALTER TABLE tour_availability ADD CONSTRAINT tour_availability_pk PRIMARY KEY ( touravailability_id );

CREATE TABLE tour_date (
    tour_date_no NUMBER(7) NOT NULL,
    port_code    NUMBER(7) NOT NULL,
    tour_no      NUMBER(7) NOT NULL,
    tour_date    DATE NOT NULL
);

COMMENT ON COLUMN tour_date.tour_date_no IS
    'Tour_date surrogate key';

COMMENT ON COLUMN tour_date.port_code IS
    'Port code';

COMMENT ON COLUMN tour_date.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour_date.tour_date IS
    'Tour date';

ALTER TABLE tour_date ADD CONSTRAINT tour_date_pk PRIMARY KEY ( tour_date_no );

ALTER TABLE tour_date
    ADD CONSTRAINT tour_date_nk UNIQUE ( port_code,
                                         tour_no,
                                         tour_date );

CREATE TABLE tour_language (
    tour_no       NUMBER(7) NOT NULL,
    port_code     NUMBER(7) NOT NULL,
    language_code CHAR(2) NOT NULL
);

COMMENT ON COLUMN tour_language.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour_language.port_code IS
    'Port code';

COMMENT ON COLUMN tour_language.language_code IS
    'Language based on ISO 639-1 Alpha-2 codes';

ALTER TABLE tour_language
    ADD CONSTRAINT tour_language_pk PRIMARY KEY ( tour_no,
                                                  port_code,
                                                  language_code );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifesst FOREIGN KEY ( cabin_number,
                                                 ship_code )
        REFERENCES cabin ( cabin_number,
                           ship_code );

ALTER TABLE passenger_address
    ADD CONSTRAINT country_passengeraddress FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE journey
    ADD CONSTRAINT cruise_journey FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE registration
    ADD CONSTRAINT cruise_regristration FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE passenger
    ADD CONSTRAINT guardian FOREIGN KEY ( guardian_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE journey
    ADD CONSTRAINT journey_port FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE passenger
    ADD CONSTRAINT language_passenger FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( op_id )
        REFERENCES operator ( op_id );

ALTER TABLE passenger
    ADD CONSTRAINT padd_passenger FOREIGN KEY ( padd_no )
        REFERENCES passenger_address ( padd_no );

ALTER TABLE manifest
    ADD CONSTRAINT passenger_manifest FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE registration
    ADD CONSTRAINT passenger_tour FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE port
    ADD CONSTRAINT port_country FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE temperature
    ADD CONSTRAINT port_temperature FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour
    ADD CONSTRAINT port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE ship
    ADD CONSTRAINT relation_13 FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE tour_date
    ADD CONSTRAINT tour_tourdate FOREIGN KEY ( tour_no,
                                               port_code )
        REFERENCES tour ( tour_no,
                          port_code );

ALTER TABLE tour
    ADD CONSTRAINT touravailability_tour FOREIGN KEY ( touravailability_id )
        REFERENCES tour_availability ( touravailability_id );

ALTER TABLE registration
    ADD CONSTRAINT tourdate_registration FOREIGN KEY ( tour_date_no )
        REFERENCES tour_date ( tour_date_no );

ALTER TABLE tour_language
    ADD CONSTRAINT tourlangauge_language FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE tour_language
    ADD CONSTRAINT tourlangauge_tour FOREIGN KEY ( tour_no,
                                                   port_code )
        REFERENCES tour ( tour_no,
                          port_code );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL off
set echo off